var walterMessage1 = 'Walter sent: “Hello. I’ve got Faceblock and Instantgam. I’m too old for the other ones.”';
    var walterMessage2 = 'Walter sent: “It was 67MB. Is that everything? I’m busy, you know.”';
      var walt = [];
  var walterSent = walterMessage1 + walterMessage2;
walt.push(walterSent.replace(/ /, '').replace( '“Hello. I’ve got ','').replace(' and ',',').replace('. I’m too old for the other ones.”Walter sent: “It was ', ',').replace('. Is that everything? I’m busy, you know.”','').replace(/sent/g,'').replace(/ /g,''));
console.log(walt);
 var jesseMessage1 = 'Jesse sent: “Yo! I’ve got ‘em all. Tooter, Faceblock, Instantgam, Snaptalk, LankedOn.”';
      var jesseMessage2 = 'Jesse sent: “Damn, it was like 300MB. Dat Snaptalk is a data hog, yo.”';
    var jess = [];
    var jesseSent = jesseMessage1 + jesseMessage2;
  jess.push(jesseSent.replace(' “Yo! I’ve got ‘em all. ','').replace(' “Damn, it was like ','').replace('. Dat Snaptalk is a data hog, yo.”','').replace(/ /g,'').replace('”',''));
console.log(jess);
  var saulMessage1 ='Saul sent: “I’m on LankedOn for Business. And I have an Instantgam account for my cats. Oh, and Faceblock for my ex-husbands.”';
      var saulMessage2 ='Saul sent: “I think 283MB. That’s what the guy at the store said. I think it means MegaBites.”';
    var saul = [];
  var saulSent = saulMessage1 + saulMessage2;
saul.push(saulSent.replace(' sent: “I’m on ',':').replace(' for Business. And I have an ',',').replace(' account for my cats. Oh, and ',',').replace(' for my ex-husbands.”Saul sent: “I think ',',').replace('. That’s what the guy at the store said. I think it means MegaBites.”',''));
console.log(saul);
    var gusMessage1 = 'Gus sent: “I use Tooter and Instantgam. My customers aren’t on the others, so I can’t get them to engage with my brand there.”';
      var gusMessage2 = 'Gus sent: “Around 150MB. I have the receipts if you need more precise figures.”';
    var gus = [];
  gusSent =  gusMessage1 + gusMessage2;
gus.push(gusSent.replace(' sent: “I use ',':').replace(' and ',',').replace('. My customers aren’t on the others, so I can’t get them to engage with my brand there.”Gus sent: “Around ',',').replace('. I have the receipts if you need more precise figures.”',''));
console.log(gus);
